# Generated by Django 3.1.4 on 2020-12-22 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 1, 45, 41, 508855)),
        ),
    ]
