# Generated by Django 3.1.4 on 2020-12-22 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201222_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 58, 16, 699362)),
        ),
    ]
