# Generated by Django 3.1.4 on 2020-12-22 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201222_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 13, 17, 24, 632681)),
        ),
    ]
