# Generated by Django 3.1.4 on 2020-12-22 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201222_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 14, 20, 8, 921194)),
        ),
    ]
