# Generated by Django 3.1.4 on 2020-12-22 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201222_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 23, 55, 42, 753159)),
        ),
    ]
