# Generated by Django 3.1.4 on 2020-12-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_identification', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=40, null=True, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
