# Generated by Django 3.1.4 on 2020-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_identification',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=40, null=True, unique=True, verbose_name='employee_id'),
        ),
    ]
