# Generated by Django 3.1.4 on 2020-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20201222_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_identification',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='employee_id'),
        ),
    ]
