# Generated by Django 3.1.4 on 2020-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201222_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_identification',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='employee_id'),
        ),
    ]
