# Generated by Django 3.1.4 on 2020-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20201222_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_identification',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='employee_identification'),
        ),
    ]
