# Generated by Django 3.1.4 on 2020-12-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20201222_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active',
        ),
        migrations.AddField(
            model_name='employee',
            name='statuses',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10, verbose_name='Statuses'),
        ),
    ]
