# Generated by Django 3.1.4 on 2020-12-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20201222_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='statuses',
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
